services:
  # -------------------------------
  # Backend: Microservicio de Autenticación
  # -------------------------------
  ms-auth:
    build: ./ms-auth
    container_name: ms-auth
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:medcoreuserpassword@db.vwqyqiffwfrxtkvtsqwq.supabase.co:5432/postgres?schema=public
      - JWT_SECRET=tu_jwt_secreto_super_seguro
      - PORT=3000
      - SMTP_USER=cristiancamiloosoriogranada@gmail.com
      - SMTP_PASSWORD=llnavznyrotndqvw
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
    networks:
      - medcore-network
    volumes:
      - ./ms-auth:/app
      - /app/node_modules
      - /app/dist
    command: npm run dev

  # -------------------------------
  # Frontend: Next.js App
  # -------------------------------
  medcore-frontend:
    build: ./medcore-frontend
    container_name: medcore-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # Accede al backend usando el nombre del servicio en la red Docker
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXTAUTH_TRUST_HOST=true
      - AUTH_SECRET=1P0whXBalPnjPzp1/WbVNCWXFEHmWwnKO0BPn+q3/zY=
      - NEXTAUTH_SECRET=1P0whXBalPnjPzp1/WbVNCWXFEHmWwnKO0BPn+q3/zY=
    depends_on:
      - ms-auth
    networks:
      - medcore-network
    volumes:
      - ./medcore-frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

# -------------------------------
# Redes
# -------------------------------
networks:
  medcore-network:
    driver: bridge